server:
  port: 8081

spring:
  application:
    name: seckill-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: spring-cloud://rgb-fk.com:8848
        username: nacos
        password: nacos
