spring:
  # mysql 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rgb-fk.com:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: blogo
    type: com.alibaba.druid.pool.DruidDataSource

  # redis配置
  redis:
    # 地址
    host: 192.168.0.101
    # 端口，默认为6379
    port: 6379
    password: qweasd
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1m

  #### thymeleaf 配置
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名

###swagger如下都是非必须的配置（实际使用时请根据实际情况配置）
swagger:
  enabled: true
  title: API文档
  description: 秒杀系统设计
#  termsOfServiceUrl: https://meander.net.cn
#  contact:
#    name: sage
#    url: www.meander.net.cn
#    email: sage@meander.net.cn
  #接口包扫描路径
  base-package: com.system.design.seckill.service.web.controller
  #需排除的接口路径
  exclude-path: /error/**

## rocketmq
rocketmq:
  isEnable: true
  name-server: localhost:9876
  access-channel: LOCAL
  producer:
    retry-next-server: true
    enable-msg-trace: true
    send-message-timeout: 3000
    group: SECKILL_ORDER
    customized-trace-topic: topic_order
