spring:
  application:
    name: seckill-business-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      # spring.cloud.nacos.discovery 配置项，使用 Nacos 作为 Spring Cloud 注册中心的配置项。默认情况下，
      # 使用 spring.application.name 作为注册的服务名。
      discovery:
        server-addr: rgb-fk.com:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rgb-fk.com:3306/seckill?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: blogo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# dubbo 配置项，Dubbo 配置项，对应 DubboConfigurationProperties 类，由 Dubbo Spring Boot 项目定义。
dubbo:
  scan:
    base-packages: com.system.design.seckill.business
  protocol:
    name: dubbo
    port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://rgb-fk.com:8848
  # dubbo.cloud 配置项，Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类。
  cloud:
    # subscribed-services 配置项，设置订阅的应用列表，默认为 * 订阅所有应用。这里，设置为 '' 表示空，不订阅任何的应用。
    subscribed-services: 'seckill-account-server' # 设置订阅的应用列表，默认为 * 订阅所有应用

kill:
  #加入一个混淆字符串(秒杀接口)的salt，为了我避免用户猜出我们的md5值，值任意给，越复杂越好
  url:
    salt: cjy20200922czz0708
rocketmq:
  name-server: 4814i260e4.zicp.vip:39938
  producer:
    group: business-group-producer
    topic: redisKillSuccess