dubbo:
  scan:
    base-packages: com.system.design.seckill
  protocol:
    name: dubbo
    port: 20884
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://rgb-fk.com:8848
spring:
  application:
    name: seckill-product-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: rgb-fk.com:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rgb-fk.com:3306/seckill?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: blogo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    database: 1
    host:
    port:
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: 10
        max-idle: 10
        min-idle: 0
    timeout: 10000


server:
  port: 8084

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

canal:
  host: 8.141.57.79
  port: 11111
  destination: example
  username:
  password:

#redis:
#  # Redis服务器地址
#  host: 127.0.0.1
#  # Redis服务器连接端口
#  port: 6379
#  # Redis服务器连接密码（默认为空）
#  password: null
#  timeout: 30000
#  # 连接池最大连接数（使用负值表示没有限制）
#  maxTotal: 30
#  # 连接池中的最大空闲连接
#  maxIdle: 10
#  numTestsPerEvictionRun: 1024
#  timeBetweenEvictionRunsMillis: 30000
#  minEvictableIdleTimeMillis: 1800000
#  softMinEvictableIdleTimeMillis: 10000
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  maxWaitMillis: 1500
#  testOnBorrow: true
#  testWhileIdle: true
#  blockWhenExhausted: false
#  JmxEnabled: true