spring:
  application:
    name: common
#dubbo:
#  application:
#    name: dubbo-test
#    qos-enable: true
#  registry:
#    address: zookeeper://192.168.0.102:2181
#  protocol:
#    name: dubbo
#    port: 21880
#  scan:
#    basePackages: com.system.design.seckill.common
