## rocketmq
rocketmq:
  name-server:
  access-channel: LOCAL
  producer:
    access-key:
    secret-key:
    retry-next-server: true
    enable-msg-trace: true
    send-message-timeout: 3000
  consumer:
    group:
    access-key:
    secret-key: